# CWE identifiers to include
cwe-ids=79

# Latest publication date to consider
cve-published-before=01/01/2026

# Earliest publication date to consider
cve-published-after=04/09/2025

# NVD API authentication key
nvd-api-key=

# GitHub API authentication key
github-api-key=

# Languages to include in the dataset
include-c-files=yes
include-cpp-files=yes
include-python-files=yes
