# CWE identifiers to include
cwe-ids=787

# Latest publication date to consider
cve-published-before=01/09/2026

# Earliest publication date to consider
cve-published-after=01/05/2026

# NVD API authentication key
nvd-api-key=

# GitHub API authentication key
github-api-key=

# Languages to include in the dataset
include-c-files=yes
include-cpp-files=yes

# Maximum directory distance for context files
context-depth=0

# Maximum number of files affected by a commit
max-files-commit=10

# Maximum number of files included in the context
max-files-context=10

# Maximum total number of files included in the dataset entry
max-files-total=10
