# CWE identifiers to include
cwe-ids=

# Latest publication date to consider
cve-published-before=

# Earliest publication date to consider
cve-published-after=

# NVD API authentication key
nvd-api-key=

# GitHub API authentication key
github-api-key=


add-c-files=yes
add-cpp-files=no
add-python-files=yes
