# --- Repository ---
mode=local
source=..
#commit=

# --- Analysis ---
granularity=line
exclude=external,benchmarks,build

# --- Execution ---
variant=seq
threads=1

# --- Output ---
json-path=../results
