mode=local
source=/home/paul/Documents/repo-analyzer/benchmarks/linux
granularity=line
json-path=/home/paul/Documents/repo-analyzer/results
variant=omp_task
threads=20
#exclude=external,benchmarks,build
